<?php
/**
 * Magento responsive theme
 *
 * @category    design
 * @package     bootstrapped_default
 * @copyright   Copyright (c) 2012 Magenthon (http://magenthon.com)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 * @author      Vedran Subotic <vedran@magenthon.com>
 */
/**
 * @var Mage_Page_Block_Html_Header $this
 */
?>
<a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
</a>
<a class="brand" href="<?php echo $this->getUrl('') ?>">
    <img src="<?php echo $this->getSkinUrl('images/tbo/logo-30x30.png') ?>"/>
    <span><?php echo $this->getLogoAlt() ?></span>
</a>
<div class="nav-collapse collapse">
    <?php echo $this->getChildHtml('topLinks') ?>
                
    <?php echo $this->getChildHtml('topSearch') ?>
</div>

<?php //echo $this->getChildHtml('topContainer'); ?>
<?php //echo $this->getChildHtml('topMenu') ?>