<?php
/**
 * Magento responsive theme
 *
 * @category    design
 * @package     bootstrapped_default
 * @copyright   Copyright (c) 2012 Magenthon (http://magenthon.com)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 * @author      Vedran Subotic <vedran@magenthon.com>
 */
?>
<div class="page-header">
    <h1><?php echo $this->__('Forgot your password?') ?></h1>
</div>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<div class="hero-unit">
    <h2><?php echo $this->__('Retrieve your password here') ?></h2>
    <form action="<?php echo $this->getUrl('*/*/forgotpasswordpost') ?>" method="post" id="form-validate">
        <fieldset>
            <legend><?php echo $this->__('Please enter your email address below. You will receive a link to reset your password.') ?></legend>
            <div class="control-group">
                <label class="control-label required" for="email_address"><?php echo $this->__('Email address') ?></label>
                <div class="controls">
                    <input name="email" id="email_address" title="<?php echo $this->__('Email address') ?>" value="<?php echo $this->htmlEscape($this->getEmailValue()) ?>" class="span4 focused required-entry validate-email" type="email"/>
                </div>
            </div>
        </fieldset>
        <div class="form-actions">
            <button type="submit" class="btn btn-large btn-warning"  title="<?php echo $this->__('Send') ?>"><?php echo $this->__('Send') ?></button>
        </div>
    </form>
</div>
<script type="text/javascript">
//<![CDATA[
    var dataForm = new VarienForm('form-validate', true);
//]]>
</script>
