<?php
/**
 * Magento responsive theme
 *
 * @category    design
 * @package     bootstrapped_default
 * @copyright   Copyright (c) 2012 Magenthon (http://magenthon.com)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 * @author      Vedran Subotic <vedran@magenthon.com>
 */
?>
<?php
/**
 * Customer onepage checkout login form template
 *
 * @see app/design/frontend/base/default/template/checkout/onepage/login.phtml
 */
/** @var $this Mage_Checkout_Block_Onepage_Login */
?>
<?php echo $this->getChildHtml('login_before')?>
<div class="row">
    <div class="span5">
        <div class="hero-unit">
            <?php echo $this->getChildHtml('login_before') ?>
            <h2><?php if ($this->getQuote()->isAllowedGuestCheckout()): ?><?php echo $this->__('Checkout as a guest or register') ?><?php else: ?><?php echo $this->__('Register to Create an Account') ?><?php endif; ?></h2>
            <p><?php echo $this->__('Register with us for future convenience.') ?></p>
            <ul>
                <li><?php echo $this->__('Fast and easy check out') ?></li>
                <li><?php echo $this->__('Easy access to your order history and status') ?></li>
            </ul>
            <?php if ($this->getQuote()->isAllowedGuestCheckout()): ?>
                <div class="control-group">
                    <div class="controls">
                        <?php if ($this->getQuote()->isAllowedGuestCheckout()): ?>
                            <label class="radio">
                                <input type="radio" name="checkout_method" id="login:guest" value="guest"<?php if ($this->getQuote()->getCheckoutMethod() == Mage_Checkout_Model_Type_Onepage::METHOD_GUEST): ?> checked="checked"<?php endif; ?> />
                                <?php echo $this->__('Checkout as guest') ?>
                            </label>
                        <?php endif; ?>
                        <label class="radio" for="login:register">
                            <input type="radio" name="checkout_method" id="login:register" value="register"<?php if ($this->getQuote()->getCheckoutMethod() == Mage_Checkout_Model_Type_Onepage::METHOD_REGISTER || !$this->getQuote()->isAllowedGuestCheckout()): ?> checked="checked"<?php endif ?> />
                            <?php echo $this->__('Register') ?>
                        </label>
                    </div>
                </div>
            <?php else: ?>
                <input type="hidden" name="checkout_method" id="login:register" value="register" checked="checked" />
            <?php endif; ?>
            <button type="button" class="btn btn-large btn-warning" onclick="checkout.setMethod();"><?php echo ($this->getQuote()->isAllowedGuestCheckout() ? $this->__('Continue') : $this->__('Register')) ?></button>
        </div>
    </div>
    <div class="span4">
        <div class="hero-unit">
            <h2><?php echo $this->__('Login') ?></h2>
            <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
            <form id="login-form" action="<?php echo $this->getPostAction() ?>" method="post" class="form">
                <fieldset>
                    <legend><?php echo $this->__('Already registered?') ?></legend>
                    <div class="control-group">
                        <label for="login-email" class="control-label required"><?php echo $this->__('Email address') ?></label>
                        <div class="controls">
                            <input type="email" class="required-entry validate-email" id="login-email" name="login[username]" value="<?php echo $this->htmlEscape($this->getUsername()) ?>" />
                        </div>
                    </div>
                    <div class="control-group">
                        <label for="login-password" class="control-label required"><?php echo $this->__('Password') ?></label>
                        <div class="controls">
                            <input type="password" class="required-entry" id="login-password" name="login[password]" />
                        </div>
                    </div>        
                    <?php echo $this->getChildHtml('persistent.remember.me'); ?>
                    <input name="context" type="hidden" value="checkout" />
                </fieldset>
                <div class="form-actions">
                    <button type="submit" class="btn btn-large" onclick="onepageLogin(this)"><?php echo $this->__('Login') ?></button>            
                    <a href="<?php echo $this->getUrl('customer/account/forgotpassword') ?>" class="pull-right"><?php echo $this->__('Forgot your password?') ?></a>
                </div>
            </form>
        </div>
    </div>
</div>
<script type="text/javascript">
//<![CDATA[
    var loginForm = new VarienForm('login-form', true);
    $('login-email').observe('keypress', bindLoginPost);
    $('login-password').observe('keypress', bindLoginPost);
    function bindLoginPost(evt){
        if (evt.keyCode == Event.KEY_RETURN) {
            loginForm.submit();
        }
    }
    function onepageLogin(button)
    {
        if(loginForm.validator && loginForm.validator.validate()){
            button.disabled = true;
            loginForm.submit();
        }
    }
//]]>
</script>
<?php
    $registerParam = $this->getRequest()->getParam('register');
    if ($registerParam || $registerParam === ''):
?>
    <script type="text/javascript">
    //<![CDATA[
        document.observe("dom:loaded", function() {
            if($('login:register')) {
                $('login:register').checked = true;
                checkout.setMethod();
            }
        })
    //]]>
    </script>
<?php endif; ?>
