<?php
/**
 * Magento responsive theme
 *
 * @category    design
 * @package     bootstrapped_default
 * @copyright   Copyright (c) 2012 Magenthon (http://magenthon.com)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 * @author      Vedran Subotic <vedran@magenthon.com>
 */
?>
<?php if ($this->isPossibleOnepageCheckout()):?>
    <a href="<?php echo $this->getCheckoutUrl() ?>" title="<?php echo $this->__('Proceed to checkout') ?>" class="btn btn-warning btn-proceed-checkout btn-large pull-right<?php if ($this->isDisabled()):?> disabled<?php endif; ?>"<?php if ($this->isDisabled()):?> disabled="disabled"<?php endif; ?>><?php echo $this->__('Proceed to checkout') ?></a>
<?php endif?>
