<?php
/**
 * Magento responsive theme
 *
 * @category    design
 * @package     bootstrapped_default
 * @copyright   Copyright (c) 2012 Magenthon (http://magenthon.com)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 * @author      Vedran Subotic <vedran@magenthon.com>
 */
?>
<?php $_width = $this->getImageWidth() ?>
<?php $current = $this->getCurrentImage() ?>
<div id="myGallery" class="carousel" <?php ?>style="width:<?php echo $_width; ?>px;"<?php ?> >
    <div class="carousel-inner">
        <?php foreach ($this->getGalleryCollection() as $image) : ?>
            <div class="<?php if ($image->getValueId() == $current->getValueId()): ?>active<?php endif; ?> item">
                <img src="<?php echo $this->helper('catalog/image')->init($this->getProduct(), 'image', $image->getFile()); ?>"<?php if ($_width): ?> width="<?php echo $_width ?>"<?php endif; ?> alt="<?php echo $this->htmlEscape($image->getLabel()) ?>" title="<?php echo $this->htmlEscape($image->getLabel()) ?>" class="image" <?php if ($image->getValueId() == $current->getValueId()): ?>id="product-gallery-image"<?php endif; ?>/>
                <?php if ($_imageTitle = $this->htmlEscape($image->getLabel())): ?>
                    <div class="carousel-caption">
                        <h1 class="image-label"><?php echo $_imageTitle ?></h1>
                    </div>
                <?php endif; ?>
            </div>
        <?php endforeach; ?>
    </div>
    <?php if ($this->getPreviusImageUrl() || $this->getNextImageUrl()): ?>
        <a href="#myGallery" data-slide="prev" class="carousel-control left">&laquo;</a>
        <a href="#myGallery" data-slide="next" class="carousel-control right">&raquo;</a>
    <?php endif; ?>
</div>
