<?php
/**
 * Magento responsive theme
 *
 * @category    design
 * @package     bootstrapped_default
 * @copyright   Copyright (c) 2012 Magenthon (http://magenthon.com)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 * @author      Vedran Subotic <vedran@magenthon.com>
 */
?>
<div id="messages_product_view"><?php echo $this->getMessagesBlock()->getGroupedHtml() ?></div>
<div class="page-title">
    <h1><?php echo Mage::helper('contacts')->__('Contact us') ?></h1>
</div>
<form action="<?php echo $this->getFormAction(); ?>" id="contactForm" method="post" class="form-horizontal">
    <fieldset>
        <div class="control-group">
            <label class="control-label required" for="name"><?php echo Mage::helper('contacts')->__('Your name') ?></label>
            <div class="controls">
                <input name="name" id="name" title="<?php echo Mage::helper('contacts')->__('Your name') ?>" value="<?php echo $this->htmlEscape($this->helper('contacts')->getUserName()) ?>" class="span4 focused required-entry" type="text" />
            </div>
        </div>
        <div class="control-group">
            <label class="control-label required" for="email"><?php echo Mage::helper('contacts')->__('Your email') ?></label>
            <div class="controls">
                <div class="input-prepend">
                    <span class="add-on"><i class="icon-envelope"></i></span><input name="email" id="email" title="<?php echo Mage::helper('contacts')->__('Your email') ?>" value="<?php echo $this->htmlEscape($this->helper('contacts')->getUserEmail()) ?>" class="span5 required-entry validate-email" type="email" />
                </div>
            </div>
        </div>
        <div class="control-group">
            <label class="control-label" for="telephone"><?php echo Mage::helper('contacts')->__('Your telephone number') ?></label>
            <div class="controls">
                <input name="telephone" id="telephone" title="<?php echo Mage::helper('contacts')->__('Your telephone number') ?>" class="span3" type="text" />
            </div>
        </div>
        <div class="control-group">
            <label class="control-label required" for="comment"><?php echo Mage::helper('contacts')->__('Your message') ?></label>
            <div class="controls">
                <textarea name="comment" id="comment" title="<?php echo Mage::helper('contacts')->__('Your message') ?>" class="input-xxlarge required-entry" cols="5" rows="3"></textarea>
            </div>
        </div>
        <div class="form-actions">
            <input type="text" name="hideit" id="hideit" value="" style="display:none !important;" />
            <button type="submit" class="btn btn-large" title="<?php echo Mage::helper('contacts')->__('Send message') ?>"><?php echo Mage::helper('contacts')->__('Send message') ?></button>
        </div>
    </fieldset>
</form>
<script type="text/javascript">
//<![CDATA[
    var contactForm = new VarienForm('contactForm', true);
//]]>
</script>
