<?php
/**
 * Magento responsive theme
 *
 * @category    design
 * @package     bootstrapped_default
 * @copyright   Copyright (c) 2012 Magenthon (http://magenthon.com)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 * @author      Vedran Subotic <vedran@magenthon.com>
 */
?>
<?php $_product = $this->getProduct(); ?>
<?php $buttonTitle = $this->__('Add to cart'); ?>
<?php if($_product->isSaleable()): ?>
    <div class="add-to-cart form-inline form-actions">
        <?php if(!$_product->isGrouped()): ?>
        <label for="qty" class="control-label"><?php echo $this->__('Qty:') ?></label>
        <input type="number" name="qty" id="qty" maxlength="12" value="<?php echo $this->getProductDefaultQty() * 1 ?>" title="<?php echo $this->__('Qty') ?>" class="qty input-small" />
        <?php endif; ?>
        <button type="button" title="<?php echo $buttonTitle ?>" class="btn btn-warning" onclick="productAddToCartForm.submit(this)"><?php echo $buttonTitle ?></button>
        <?php echo $this->getChildHtml('', true, true) ?>
    </div>
<?php endif; ?>