<?php
/**
 * Magento responsive theme
 *
 * @category    design
 * @package     bootstrapped_default
 * @copyright   Copyright (c) 2012 Magenthon (http://magenthon.com)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 * @author      Vedran Subotic <vedran@magenthon.com>
 */
?>
<div class="dashboard">
    <div class="page-header">
        <h1><?php echo $this->__('My dashboard') ?></h1>
    </div>
    <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
    <?php echo $this->getChildHtml('hello') ?>
    <?php echo $this->getChildHtml('top') ?>
    <h2><?php echo $this->__('Account information') ?></h2>
    <?php echo $this->getChildHtml('info') ?>
    <?php echo $this->getChildHtml('address') ?>
    <?php echo $this->getChildHtml('info1') ?>
    <?php echo $this->getChildHtml('info2') ?>
</div>
