<?php
/**
 * Magento responsive theme
 *
 * @category    design
 * @package     bootstrapped_default
 * @copyright   Copyright (c) 2012 Magenthon (http://magenthon.com)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 * @author      Vedran Subotic <vedran@magenthon.com>
 */
?>
<div class="row-fluid">
    <div class="span12">
        <h3><?php echo $this->__('Address book') ?></h3>
        <p><a href="<?php echo $this->getAddressBookUrl() ?>"><?php echo $this->__('Manage addresses') ?></a></p>
    </div>
</div>
<div class="row-fluid">
    <div class="span6 well">
        <h4><?php echo $this->__('Default billing address') ?></h4>
        <address>
            <?php echo $this->getPrimaryBillingAddressHtml() ?><br />
            <a href="<?php echo $this->getPrimaryBillingAddressEditUrl() ?>"><?php echo $this->__('Edit address') ?></a>
        </address>
    </div>
    <div class="span6 well">
        <h4><?php echo $this->__('Default shipping address') ?></h4>
        <address>
            <?php echo $this->getPrimaryShippingAddressHtml() ?><br />
            <a href="<?php echo $this->getPrimaryShippingAddressEditUrl() ?>"><?php echo $this->__('Edit address') ?></a>
        </address>
    </div>
</div>
