<?php
/**
 * Magento responsive theme
 *
 * @category    design
 * @package     bootstrapped_default
 * @copyright   Copyright (c) 2012 Magenthon (http://magenthon.com)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 * @author      Vedran Subotic <vedran@magenthon.com>
 */
?>
<div class="row-fluid">
    <div class="span6 well">
        <h3><?php echo $this->__('Contact information') ?></h3>
        <p><a href="<?php echo $this->getUrl('customer/account/edit') ?>"><?php echo $this->__('Edit') ?></a></p>
        <p><?php echo $this->htmlEscape($this->getCustomer()->getName()) ?><br/>
        <a href="#"><?php echo $this->htmlEscape($this->getCustomer()->getEmail()) ?></a></p>
        <p><a href="<?php echo $this->getChangePasswordUrl() ?>"><?php echo $this->__('Change password') ?></a></p>
    </div>
    <div class="span6 well">
        <?php if( $this->isNewsletterEnabled() ): ?>
        <h3><?php echo $this->__('Newsletters') ?></h3>
        <p><a href="<?php echo $this->getUrl('newsletter/manage') ?>"><?php echo $this->__('Edit') ?></a></p>
        <p>
            <?php if( $this->getIsSubscribed() ): ?>
                <?php echo $this->__("You are currently subscribed to <code>Newsletter</code>.") ?>
            <?php else: ?>
                <?php echo $this->__('You are currently not subscribed to any newsletter.') ?>
            <?php endif; ?>
        </p>
        <?php endif; ?>
    </div>
</div>
