<?php
/**
 * Magento responsive theme
 *
 * @category    design
 * @package     bootstrapped_default
 * @copyright   Copyright (c) 2012 Magenthon (http://magenthon.com)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 * @author      Vedran Subotic <vedran@magenthon.com>
 */
?>
<div class="block block-subscribe">
    <form action="<?php echo $this->getFormActionUrl() ?>" method="post" id="newsletter-validate-detail" class="form well">
        <fieldset>
            <div class="control-group">
                <label for="newsletter" class="control-label"><?php echo $this->__('Sign up for our email newsletter') ?></label>
                <div class="controls">
                    <div class="input-prepend input-append">
                        <span class="add-on"><i class="icon-envelope"></i></span>
                        <input type="email" name="email" id="newsletter" required="required" placeholder="<?php echo $this->helper('newsletter')->__('Enter your email address') ?>" class="span2"/><button type="submit" class="btn btn-inverse"><?php echo $this->__('Go') ?></button>
                    </div>
                </div>
            </div>
        </fieldset>
    </form>
    <script type="text/javascript">
    //<![CDATA[
        var newsletterSubscriberFormDetail = new VarienForm('newsletter-validate-detail');
    //]]>
    </script>
</div>