<?php
/**
 * Magento responsive theme
 *
 * @category    design
 * @package     bootstrapped_default
 * @copyright   Copyright (c) 2012 Magenthon (http://magenthon.com)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 * @author      Vedran Subotic <vedran@magenthon.com>
 */
?>
    <div class="discount">
        <h2><?php echo $this->__('Discount codes') ?></h2>
    </div>
<form id="discount-coupon-form" action="<?php echo $this->getUrl('checkout/cart/couponPost') ?>" method="post" class="form-inline discount-coupon-form">
    <fieldset>
        <legend for="coupon_code"><?php echo $this->__('Enter your coupon code if you have one.') ?></legend>        
        <div>
            <input type="hidden" name="remove" id="remove-coupone" value="0" />
            <input class="span3" id="coupon_code" name="coupon_code" value="<?php echo $this->htmlEscape($this->getCouponCode()) ?>" type="text"/>
            <button type="button" title="<?php echo $this->__('Apply coupon') ?>" class="btn pull-right" onclick="discountForm.submit(false)" value="<?php echo $this->__('Apply coupon') ?>"><?php echo $this->__('Apply coupon') ?></button>
            <?php if(strlen($this->getCouponCode())): ?>
                &nbsp; <button type="button" title="<?php echo $this->__('Cancel coupon') ?>" class="button" onclick="discountForm.submit(true)" value="<?php echo $this->__('Cancel coupon') ?>"><?php echo $this->__('Cancel coupon') ?></button>
            <?php endif;?>
        </div>
    </fieldset>
</form>
<script type="text/javascript">
//<![CDATA[
var discountForm = new VarienForm('discount-coupon-form');
discountForm.submit = function (isRemove) {
    if (isRemove) {
        $('coupon_code').removeClassName('required-entry');
        $('remove-coupone').value = "1";
    } else {
        $('coupon_code').addClassName('required-entry');
        $('remove-coupone').value = "0";
    }
    return VarienForm.prototype.submit.bind(discountForm)();
}
//]]>
</script>
